# @url=http://localhost:3001
# @url=https://serverless-neq2kr3vhq-de.a.run.app
@url=http://localhost:8080
# @url=https://serverless.credot.ml

################################################################
GET {{url}}/api/host

########
GET {{url}}/api/version

#####
GET {{url}}/api/redirect